#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
#npm run check-format ||
#(
#    echo '[+] Prettier Check Failed. Run npm run format, add changes and try commit again.';
#    false;
#)

# Check ESLint Standards
#npm run check-lint ||
#(
#    echo '[+] ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
#    false; 
#)

# Check tsconfig standards
#npm run check-types ||
#(
#    echo '[+] TS config standards failed, Fix the errors listed and try to commit again'
#    false;
#)

#npm run test ||
#(
#   echo '[+] Unit tests failed'
#   false;
#)

#npm run build ||
#(
#    echo '[+] Build failed'
#    false;
#)

# If everything passes... Now we can commit
echo '[+] Committing this now.'